config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root to: 'home#index'
  get 'home/index'
  get 'home/contacto'
  get 'home/recursos'
  get 'home/somos'
  get 'home/mision'
  get 'home/radio'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  
    render 'index'
  end
  def mision
  end
  def somos
  end
  def contacto
  end
  def recursos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contacto.html.erb
<h1>Contactos</h1>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
<div class="container">
	<div class="row justify-content-center">
		<div class="col-12 col-md-8 col-lg-6 pb-5">


                    <!--Form with header-->

                    <form action="mail.php" method="post">
                        <div class="card border-primary rounded-0">
                            <div class="card-header p-0">
                                <div class="bg-info text-white text-center py-2">
                                    <h3><i class="fa fa-envelope"></i> Contactanos</h3>
                                    <p class="m-0">Con gusto te ayudaremos</p>
                                </div>
                            </div>
                            <div class="card-body p-3">

                                <!--Body-->
                                <div class="form-group">
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-user text-info"></i></div>
                                        </div>
                                        <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre y Apellido" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-envelope text-info"></i></div>
                                        </div>
                                        <input type="email" class="form-control" id="nombre" name="email" placeholder="ejemplo@gmail.com" required>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-comment text-info"></i></div>
                                        </div>
                                        <textarea class="form-control" placeholder="Envianos tu Mensaje" required></textarea>
                                    </div>
                                </div>

                                <div class="text-center">
                                    <input type="submit" value="Enviar" class="btn btn-info btn-block rounded-0 py-2">
                                </div>
                            </div>

                        </div>
                    </form>
                    <!--Form with header-->


                </div>
	</div>
</div>

app/views/home/mision.html.erb
<div class="container">
	<div class="row" align="center">
		<div class ="col-md-12" >
			<div class="jumbotron">
			  <h1>Mision</h1>
			  <p>Orientación familiar una guía para el hogar es un espacio Televisivo y radial con la misión de llegar a todos los hogares a fin de compartir valores familiares, educativos y espirituales con la colaboración de diferentes comunidades con el propósito de que reine la buena convivencia al recibir mensaje conciliador de paz y armonía través de consejeria , orientación y buena guía.</p>
			  <p><a class="btn btn-primary btn-lg" href="#" role="button"></a>
			  </p>
			</div>
		</div>
		<div class ="col-md-12" >
		<div srcset="https://dummyimage.com/600x500/007aeb/4196e5" alt="responsive image" class="d-block img-fluid"><%= link_to image_tag "comunidad.jpg" , class: "img"%>
			
		</div>
		</div>
	</div>
</div>

app/views/home/radio.html.erb
 
 
 <!Doctype>
<html>
<head>
  <style>
    .fishes
    {
      position: relative;
      top: 0;
      left: 0;
    }
    .fish
    {
      position: absolute;
      top: -20px;
      left: 80px;
    }
  </style>
</head>
<body>
  <div style="position: relative; left: 0; top: 0;">
<iframe src= 'https://www.youtube.com/channel/UCy8RQ-Rm1da7kGN0TyVlWxg/videos' frameborder='0' width='100%' height='1000'></iframe>
<div class = "fishes">
   <%= image_tag("radio.jpg", width: "550", height: "350", alt: "Edit Entry") %> 
</div>
<div ="fish">
    <iframe src="https://cdn.voscast.com/player/player.php?host=s8.voscast.com&amp;port=8106" scrolling="no" width="150" height="30" frameborder="0"></iframe>
</div>
  </div>
</body>
</html>

app/views/home/recursos.html.erb
<h1>Recursos</h1>


<div class="region--sidebar-second region region-sidebar-second">
    <div id="block-gethelp" class="block block-block-content block-block-contentd0089eef-125e-4a65-9ccf-db5759878e91">
            
  <h2 class="visually-hidden">Get Help</h2>
  

  <div class="block-content">
          
            <div class="clearfix text-formatted field field--name-body field--type-text-with-summary field--label-hidden field__item"><p><a href="//www.mentalhealth.gov/get-help/immediate-help" id="anch_53"><img alt="Get Immediate Help" data-entity-type="file" data-entity-uuid="2babeadf-3362-47de-b894-cb07363cc59a" src="//www.mentalhealth.gov/sites/default/files/inline-images/GetHelp.jpg"></a></p>
</div>
      
      </div>
</div>





<div id="block-suicidelifeline" class="helpline block block-block-content block-block-content0606afb9-8eea-4b20-933b-7910f7868704">
            
  <h2 class="visually-hidden">Suicide Lifeline</h2>
  

  <div class="block-content">
          
            <div class="clearfix text-formatted field field--name-body field--type-text-with-summary field--label-hidden field__item"><p><a href="http://www.suicidepreventionlifeline.org/" id="anch_54"><img alt="National Suicide Prevention Lifeline. 1-800-273-8255(TALK)" data-entity-type="file" data-entity-uuid="10b96f05-0e34-4e1a-a6ad-a654b0c2b97d" src="//www.mentalhealth.gov/sites/default/files/inline-images/suicide-helpline.jpg"></a></p>

<h3>1-800-273-8255 (TALK)</h3>
</div>
      
      </div>
</div>





<div id="block-veteranscrisisline" class="block block-block-content block-block-content902d2416-1d06-42ef-a2f4-ff0692fb817b">
            
  <h2 class="visually-hidden">Veterans Crisis Line</h2>
  

  <div class="block-content">
          
            <div class="clearfix text-formatted field field--name-body field--type-text-with-summary field--label-hidden field__item"><p><a href="https://www.veteranscrisisline.net/" id="anch_55"><img alt="Veterans Crisis Line. 1-800-273-8255. Press 1." data-entity-type="file" data-entity-uuid="ce355f19-3c72-482b-bd05-56cd3f6f3973" src="//www.mentalhealth.gov/sites/default/files/inline-images/VeteransCrisisLine.jpg"></a></p>
</div>
      
      </div>
</div>






  </div>

app/views/home/somos.html.erb
<h1>Quienes Somos</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
  <head>
    <title>Orientacion</title>

    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<body >

 

<div align= "center">
<nav class="navbar navbar-expand-lg navbar-light bg-light " >

  <a class="navbar-brand" href="#"><%= image_tag "banner_burned.png",  class: "icon" %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon">

  </span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent" style = "margin-left: 8%";>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <div class="nav-link" href="#"><%= link_to 'Inicio', root_path %><span class="sr-only">(current)</span></div>
      </li>
      <li class="nav-item">
        <div class="nav-link" href="#"><%= link_to 'Mision', home_mision_path %></div>
      </li>

      <li class="nav-item">
        <div class="nav-link" href="#"><%= link_to 'Contacto', home_contacto_path %></div>
      </li>
      <li>
       <div class="nav-link" href="#"> <%= link_to 'Recursos', home_recursos_path %></div>
      </li>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Radio</a>
          <a class="dropdown-item" href="#">TV</a>
        </div>
      </li>
       <li class="nav-item">
        <div class="nav-link " href="#"><%= link_to 'Quienes Somos', home_somos_path %></div>
      </li>
      </li>
       <li class="nav-item">
        <div class="nav-link " href="#"><%= link_to 'TV y Radio', home_radio_path %></div>
      </li>
      
     
    </ul>
 
  </div>

</nav>

</div>


  </head>

  <body>

      

  <div align= "center">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <%= yield %>
   </div>
  


  </body>
<!-- Footer -->
  <section id="footer" style = "margin-top:20%"">
    <div class="container">
      <div class="row text-center text-xs-center text-sm-left text-md-left">
        <div class="col-xs-12 col-sm-4 col-md-4">
          <h5>Quick links</h5>
          <ul class="list-unstyled quick-links">
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Home</a></li>
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>About</a></li>
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Get Started</a></li>
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Videos</a></li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4">
          <h5>Quick links</h5>
          <ul class="list-unstyled quick-links">
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Home</a></li>
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>About</a></li>
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Get Started</a></li>
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Videos</a></li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4">
          <h5>Quick links</h5>
          <ul class="list-unstyled quick-links">
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Home</a></li>
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>About</a></li>
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
            <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Get Started</a></li>
            <li><a href="https://wwwe.sunlimetech.com" title="Design and developed by"><i class="fa fa-angle-double-right"></i>Imprint</a></li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
          <ul class="list-unstyled list-inline social text-center">
            <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-facebook"></i></a></li>
            <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-google-plus"></i></a></li>
            <li class="list-inline-item"><a href="javascript:void();" target="_blank"><i class="fa fa-envelope"></i></a></li>
          </ul>
        </div>
        </hr>
      </div>  
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
          <p><u><a href="https://www.nationaltransaction.com/">Orientacion Familiar es una 
          institucion registrada bajo la direccion de Dr. Jose Gil y incorporatda en Hazleton PA. </p>
          <p class="h6">&copy All right Reversed.<a class="text-green ml-2" href="https://www.sunlimetech.com" target="_blank">Orientacion Familiar</a></p>
        </div>
        </hr>
      </div>  
    </div>
  </section>

  </body>
</html>


<aside class= 'lx-4 xl-3 c-static-advert-rigth-area'>

</aside>